### ISSUE TITLE
How was `xkbcommon/keysyms_linux.go` generated?

### ISSUE THREAD

**Issue by vanguacamolie** [neurlang/wayland#6]
Hello, thanks for creating this library! I am not using this library since I'm not creating a Wayland client, but I am integrating with `libxkbcommon`, for which your project has been a helpful example.

But I do wonder, how did you generate [`xkbcommon/keysyms_linux.go`](https://github.com/neurlang/wayland/blob/4f8518b6aacd889b0f4a8db5cd5720665b9d98dc/xkbcommon/keysyms_linux.go)? It says it is autogenerated, but I can't figure out using what method. I'm trying to create a similar file to use with my own project.

**Comment by neurlang** [comment]
Hello, as the (now dead) url at the comment in the top of the file says, this file was ported from the original C version of file, mostly using search and replace:

https://xkbcommon.org/doc/0.2.0/xkbcommon-keysyms_8h_source.html

I don't have any script to autogenerate or port the file, the comment about being autogenerated is from the original c version.
